source 'https://rubygems.org'

ruby '3.2.11'

gem 'rails', '~> 7.1.3'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rdkafka', '~> 0.15.0'
gem 'bcrypt', '~> 3.1'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
end
